import React from "react";
import { Container, Row, Col, Image, Form } from "react-bootstrap";

function Directories() {
  const divStyles = {
    backgroundColor: "#272A38",
    padding: "1rem",
    borderRadius: "14px",
    height: "100%",
  };

  return (
    <Container
      style={{
        paddingTop: "6rem",
      }}
    >
      <Row>
        {directories.map(({ title, description }, index) => (
          <Col xs={12} md={6} key={index} className="pb-4 pb-md-0">
            <div style={divStyles}>
              <h6
                style={{
                  color: "#FFFFFF",
                  fontWeight: "600",
                  fontSize: "clamp(0.8rem, 0.8rem + 1.5vw, 1.5rem)",
                }}
              >
                {title}
              </h6>
              <div>
                {description.map((list, index) => (
                  <ul
                    className="normalPTag"
                    style={{ color: "#ECECEC" }}
                    key={index}
                  >
                    <li>{list}</li>
                  </ul>
                ))}
              </div>
            </div>
          </Col>
        ))}
      </Row>
    </Container>
  );
}

export default Directories;

const directories = [
  {
    title: "Directory Title",
    description: [
      "Enter Your Query: Type or speak your search query into the input field to find projects matching your interests, technology stack, or industry focus.",
      "Review Results: Explore tailored project suggestions with summaries and relevant details generated by ChatGPT based on your preferences.",
    ],
  },
  {
    title: "Directory Title",
    description: [
      "Enter Your Query: Type or speak your search query into the input field to find projects matching your interests, technology stack, or industry focus.",
      "Refine Your Search: Fine-tune your search by entering specific keywords or criteria to get more precise results adjusted by ChatGPT.",
    ],
  },
];
