import React from "react";
import { Container, Row, Col, Image, Form } from "react-bootstrap";
import images from "../../../../constants/images";

function AiTools() {
  const divStyles = {
    backgroundColor: "#272A38",
    padding: "1rem",
    borderRadius: "14px",
    height: "100%",
  };

  return (
    <Container
      style={{
        paddingTop: "6rem",
      }}
    >
      <Row>
        {Ai.map(({ image, name, description }, index) => (
          <Col xs={12} md={6} key={index} className="pb-4 pb-md-0">
            <div style={divStyles}>
              <div className="d-flex flex-column gap-3 flex-md-row">
                <div>
                  <Image src={image} />
                </div>

                <div>
                  <div className="d-flex justify-content-between mb-1">
                    <h6
                      style={{
                        color: "#FFFFFF",
                        fontWeight: "600",
                        fontSize: "clamp(0.8rem, 0.8rem + 1.5vw, 1.5rem)",
                      }}
                    >
                      {name}
                    </h6>
                    <Form>
                      <Form.Check type="switch" id="custom-switch" />
                    </Form>
                  </div>

                  <div>
                    {description.map((list, index) => (
                      <ul
                        className="normalPTag"
                        style={{ color: "#ECECEC" }}
                        key={index}
                      >
                        <li>{list}</li>
                      </ul>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </Col>
        ))}
      </Row>
    </Container>
  );
}

export default AiTools;

const Ai = [
  {
    id: "01",
    image: images.gptLogo.src,
    name: "ChatGPT 3.0",
    description: [
      "Enter Your Query: Type or speak your search query into the input field to find projects matching your interests, technology stack, or industry focus.",
      "Review Results: Explore tailored project suggestions with summaries and relevant details generated by ChatGPT based on your preferences.",
      "Refine Your Search: Fine-tune your search by entering specific keywords or criteria to get more precise results adjusted by ChatGPT.",
    ],
  },
  {
    image: images.gptLogo.src,
    name: "Meta Ai",
    description: [
      "Enter Your Query: Type or speak your search query into the input field to find projects matching your interests, technology stack, or industry focus.",
      "Review Results: Explore tailored project suggestions with summaries and relevant details generated by ChatGPT based on your preferences.",
      "Refine Your Search: Fine-tune your search by entering specific keywords or criteria to get more precise results adjusted by ChatGPT.",
    ],
  },
];
